# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: morpho-indexer
description: Morpho Protocol Indexer

contracts:
  - name: Morpho
    abi_file_path: ./abis/MorphoBlue.json
    handler: ./src/handlers/MorphoBlue.ts
    events:
      - event: "CreateMarket(bytes32 indexed id, (address, address, address, address, uint256) marketParams)"
      - event: "SetFee(bytes32 indexed id, uint256 newFee)"
      - event: "AccrueInterest(bytes32 indexed id, uint256 prevBorrowRate, uint256 interest, uint256 feeShares)"
      - event: "Supply(bytes32 indexed id, address indexed caller, address indexed onBehalf, uint256 assets, uint256 shares)"
      - event: "Withdraw(bytes32 indexed id, address caller, address indexed onBehalf, address indexed receiver, uint256 assets, uint256 shares)"
      - event: "SupplyCollateral(bytes32 indexed id, address indexed caller, address indexed onBehalf, uint256 assets)"
      - event: "WithdrawCollateral(bytes32 indexed id, address caller, address indexed onBehalf, address indexed receiver, uint256 assets)"
      - event: "Borrow(bytes32 indexed id, address caller, address indexed onBehalf, address indexed receiver, uint256 assets, uint256 shares)"
      - event: "Repay(bytes32 indexed id, address indexed caller, address indexed onBehalf, uint256 assets, uint256 shares)"
      - event: "Liquidate(bytes32 indexed id, address indexed caller, address indexed borrower, uint256 repaidAssets, uint256 repaidShares, uint256 seizedAssets, uint256 badDebtAssets, uint256 badDebtShares)"
      - event: "SetAuthorization(address indexed caller, address indexed authorizer, address indexed authorized, bool newIsAuthorized)"

  - name: MetaMorphoFactory
    abi_file_path: ./abis/MetaMorphoFactory.json
    handler: ./src/handlers/MetaMorpho.ts
    events:
      - event: "CreateMetaMorpho(address indexed metaMorpho, address indexed caller, address initialOwner, uint256 initialTimelock, address indexed asset, string name, string symbol, bytes32 salt)"

  - name: MetaMorpho
    abi_file_path: ./abis/MetaMorpho.json
    handler: ./src/handlers/MetaMorpho.ts
    events:
      - event: "OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner)"
      - event: "OwnershipTransferred(address indexed previousOwner, address indexed newOwner)"
      - event: "SubmitCap(address indexed caller, bytes32 indexed id, uint256 cap)"
      - event: "SubmitGuardian(address indexed newGuardian)"
      - event: "SubmitMarketRemoval(address indexed caller, bytes32 indexed id)"
      - event: "SubmitTimelock(uint256 newTimelock)"
      - event: "RevokePendingCap(address indexed caller, bytes32 indexed id)"
      - event: "RevokePendingGuardian(address indexed caller)"
      - event: "RevokePendingMarketRemoval(address indexed caller, bytes32 indexed id)"
      - event: "RevokePendingTimelock(address indexed caller)"
      - event: "SetCap(address indexed caller, bytes32 indexed id, uint256 cap)"
      - event: "SetCurator(address indexed newCurator)"
      - event: "SetFee(address indexed caller, uint256 newFee)"
        name: SetVaultFee
      - event: "SetFeeRecipient(address indexed newFeeRecipient)"
      - event: "SetGuardian(address indexed caller, address indexed guardian)"
      - event: "SetIsAllocator(address indexed allocator, bool isAllocator)"
      - event: "SetName(string name)"
      - event: "SetSkimRecipient(address indexed newSkimRecipient)"
      - event: "SetSymbol(string symbol)"
      - event: "SetTimelock(address indexed caller, uint256 newTimelock)"
      - event: "SetSupplyQueue(address indexed caller, bytes32[] newSupplyQueue)"
      - event: "SetWithdrawQueue(address indexed caller, bytes32[] newWithdrawQueue)"
      - event: "Transfer(address indexed from, address indexed to, uint256 value)"
      - event: "UpdateLastTotalAssets(uint256 updatedTotalAssets)"
      - event: "UpdateLostAssets(uint256 newLostAssets)"

  - name: AdaptiveCurveIRM
    abi_file_path: ./abis/AdaptiveCurveIrm.json
    handler: ./src/handlers/AdaptiveCurveIrm.ts
    events:
      - event: "BorrowRateUpdate(bytes32 indexed id, uint256 avgBorrowRate, uint256 rateAtTarget)"

  - name: PreLiquidationFactory
    abi_file_path: ./abis/PreLiquidationFactory.json
    handler: ./src/handlers/PreLiquidationFactory.ts
    events:
      - event: "CreatePreLiquidation(address indexed preLiquidation, bytes32 id, (uint256, uint256, uint256, uint256, uint256, address) preLiquidationParams)"

chains:
  - id: 1 # mainnet
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0xBBBBBbbBBb9cC5e90e3b3Af64bdAF62C37EEFFCb
        start_block: 18883124
      - name: MetaMorphoFactory
        address:
          - 0x1897A8997241C1cD4bD0698647e4EB7213535c24
          - 0xA9c3D3a366466Fa809d1Ae982Fb2c46E5fC41101
        start_block: 18925584
      - name: MetaMorpho
        start_block: 18925584
      - name: AdaptiveCurveIRM
        address:
          - 0x870aC11D48B15DB9a138Cf899d20F13F79Ba00BC
        start_block: 18883124
      - name: PreLiquidationFactory
        address:
          - 0x6FF33615e792E35ed1026ea7cACCf42D9BF83476
        start_block: 21414664

  - id: 8453 # base
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0xBBBBBbbBBb9cC5e90e3b3Af64bdAF62C37EEFFCb
        start_block: 13977148
      - name: MetaMorphoFactory
        address:
          - 0xFf62A7c278C62eD665133147129245053Bbf5918
          - 0xA9c3D3a366466Fa809d1Ae982Fb2c46E5fC41101
        start_block: 13978134
      - name: MetaMorpho
        start_block: 13978134
      - name: AdaptiveCurveIRM
        address:
          - 0x46415998764C29aB2a25CbeA6254146D50D22687
        start_block: 13977152
      - name: PreLiquidationFactory
        address:
          - 0x8cd16b62E170Ee0bA83D80e1F80E6085367e2aef
        start_block: 23779056

  - id: 130 # unichain
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0x8f5ae9CddB9f68de460C77730b018Ae7E04a140A
        start_block: 9139027
      - name: MetaMorphoFactory
        address:
          - 0xe9EdE3929F43a7062a007C3e8652e4ACa610Bdc0
        start_block: 9316789
      - name: MetaMorpho
        start_block: 9316789
      - name: AdaptiveCurveIRM
        address:
          - 0x9a6061d51743B31D2c3Be75D83781Fa423f53F0E
        start_block: 9139027
      - name: PreLiquidationFactory
        address:
          - 0xb04e4D3D59Ee47Ca9BA192707AF13A7D02969911
        start_block: 9381237

  - id: 137 # polygon
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0x1bF0c2541F820E775182832f06c0B7Fc27A25f67
        start_block: 66931042
      - name: MetaMorphoFactory
        address:
          - 0xa9c87daB340631C34BB738625C70499e29ddDC98
        start_block: 66931118
      - name: MetaMorpho
        start_block: 66931118
      - name: AdaptiveCurveIRM
        address:
          - 0xe675A2161D4a6E2de2eeD70ac98EEBf257FBF0B0
        start_block: 66931042
      - name: PreLiquidationFactory
        address:
          - 0xeDadDe37D76c72b98725614d0b41C20Fe612d304
        start_block: 68074185

  - id: 42161 # arbitrum
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0x6c247b1F6182318877311737BaC0844bAa518F5e
        start_block: 296446593
      - name: MetaMorphoFactory
        address:
          - 0x878988f5f561081deEa117717052164ea1Ef0c82
        start_block: 296447195
      - name: MetaMorpho
        start_block: 296447195
      - name: AdaptiveCurveIRM
        address:
          - 0x937Ce2d6c488b361825D2DB5e8A70e26d48afEd5
        start_block: 296446593
      - name: PreLiquidationFactory
        address:
          - 0x635c31B5DF1F7EFbCbC07E302335Ef4230758e3d
        start_block: 307326238

  - id: 10 # optimism
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0xce95AfbB8EA029495c66020883F87aaE8864AF92
        start_block: 130770075
      - name: MetaMorphoFactory
        address:
          - 0x3Bb6A6A0Bc85b367EFE0A5bAc81c5E52C892839a
        start_block: 130770189
      - name: MetaMorpho
        start_block: 130770189
      - name: AdaptiveCurveIRM
        address:
          - 0x8cD70A8F399428456b29546BC5dBe10ab6a06ef6
        start_block: 130770075
      - name: PreLiquidationFactory
        address:
          - 0x3d05C01EE8e97361b9E19D172128255eaE5F98B9
        start_block: 132139369

  - id: 2741 # abstract
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0xc85CE8ffdA27b646D269516B8d0Fa6ec2E958B55
        start_block: 13947713
      - name: MetaMorphoFactory
        address:
          - 0x83A7f60c9fc57cEf1e8001bda98783AA1A53E4b1
        start_block: 13949369
      - name: MetaMorpho
        start_block: 13949369
      - name: AdaptiveCurveIRM
        address:
          - 0xd334eb112CfD1EB4a50FB871b7D9895EBB955C43
        start_block: 13947713
      - name: PreLiquidationFactory
        address:
          - 0x1058DA51242dF63bA3A61c838A61405ea6Edb083
        start_block: 13949482

  - id: 42220 # celo
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0xd24ECdD8C1e0E57a4E26B1a7bbeAa3e95466A569
        start_block: 40249329
      - name: MetaMorphoFactory
        address:
          - 0x6870aA9f66C1e5Efe8Dbe8730e86E9e91f688275
        start_block: 40259931
      - name: MetaMorpho
        start_block: 40259931
      - name: AdaptiveCurveIRM
        address:
          - 0x683CAAADdfA2F42e24880E202676526d501a5dED
        start_block: 40249329
      - name: PreLiquidationFactory
        address:
          - 0x717a3eF7D366F5ce4636011924D0Bd65ea5eCE2f
        start_block: 41808392

  - id: 252 # fraxtal
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0xa6030627d724bA78a59aCf43Be7550b4C5a0653b
        start_block: 15317931
      - name: MetaMorphoFactory
        address:
          - 0x27D4Af0AC9E7FDfA6D0853236f249CC27AE79488
        start_block: 15318007
      - name: MetaMorpho
        start_block: 15318007
      - name: AdaptiveCurveIRM
        address:
          - 0xA0D4D77b5D9933073572E19C172BFE866312673b
        start_block: 15317931
      - name: PreLiquidationFactory
        address:
          - 0x373ccddcd3F09D2e1430B3F2b290B9bF56Ae7336
        start_block: 16536231

  - id: 57073 # ink
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0x857f3EefE8cbda3Bc49367C996cd664A880d3042
        start_block: 4078776
      - name: MetaMorphoFactory
        address:
          - 0xd3f39505d0c48AFED3549D625982FdC38Ea9904b
        start_block: 4078830
      - name: MetaMorpho
        start_block: 4078830
      - name: AdaptiveCurveIRM
        address:
          - 0x9515407b1512F53388ffE699524100e7270Ee57B
        start_block: 4078776
      - name: PreLiquidationFactory
        address:
          - 0x30607fEa77168d2c0401B6f60F0B40E32F9339E3
        start_block: 6385077

  - id: 1135 # lisk
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0x00cD58DEEbd7A2F1C55dAec715faF8aed5b27BF8
        start_block: 15731231
      - name: MetaMorphoFactory
        address:
          - 0x01dD876130690469F685a65C2B295A90a81BaD91
        start_block: 15731333
      - name: MetaMorpho
        start_block: 15731333
      - name: AdaptiveCurveIRM
        address:
          - 0x5576629f21D528A8c3e06C338dDa907B94563902
        start_block: 15731231
      - name: PreLiquidationFactory
        address:
          - 0xF2c325F26691b6556e6f66451bb38bDa37FEbaa7
        start_block: 15731595

  - id: 34443 # mode
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0xd85cE6BD68487E0AaFb0858FDE1Cd18c76840564
        start_block: 19983370
      - name: MetaMorphoFactory
        address:
          - 0xae5b0884bfff430493D6C844B9fd052Af7d79278
        start_block: 19983443
      - name: MetaMorpho
        start_block: 19983443
      - name: AdaptiveCurveIRM
        address:
          - 0xE3d46Ae190Cb39ccA3655E966DcEF96b4eAe1d1c
        start_block: 19983370
      - name: PreLiquidationFactory
        address:
          - 0x249E4808264c545861e43728186a731dE7c7D745
        start_block: 19983599

  - id: 98866 # plume
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0x42b18785CE0Aed7BF7Ca43a39471ED4C0A3e0bB5
        start_block: 765994
      - name: MetaMorphoFactory
        address:
          - 0x2525D453D9BA13921D5aB5D8c12F9202b0e19456
        start_block: 766078
      - name: MetaMorpho
        start_block: 766078
      - name: AdaptiveCurveIRM
        address:
          - 0x7420302Ddd469031Cd2282cd64225cCd46F581eA
        start_block: 765994
      - name: PreLiquidationFactory
        address:
          - 0xF184156Cf6Ad4D3dA7F6449D40755A0f9de97ef3
        start_block: 789925

  - id: 534352 # scroll
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0x2d012EdbAdc37eDc2BC62791B666f9193FDF5a55
        start_block: 12842868
      - name: MetaMorphoFactory
        address:
          - 0x56b65742ade55015e6480959808229Ad6dbc9295
        start_block: 12842903
      - name: MetaMorpho
        start_block: 12842903
      - name: AdaptiveCurveIRM
        address:
          - 0xa5EA7500A27C0079961D93366A6e93aafF18CB90
        start_block: 12842868
      - name: PreLiquidationFactory
        address:
          - 0xeD960178e4aDA0296786Fa79D84e8FDF7bd44B25
        start_block: 13504587

  - id: 1329 # sei
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0xc9cDAc20FCeAAF616f7EB0bb6Cd2c69dcfa9094c
        start_block: 166036723
      - name: MetaMorphoFactory
        address:
          - 0x8Dea49ec5bd5AeAc8bcf96B3E187F59354118291
        start_block: 168896078
      - name: MetaMorpho
        start_block: 168896078
      - name: AdaptiveCurveIRM
        address:
          - 0x6eFA8e3Aa8279eB2fd46b6083A9E52dA72EA56c4
        start_block: 166036723
      - name: PreLiquidationFactory
        address:
          - 0x65eD61058cEB4895B7d62437BaCEA39b04f6D27B
        start_block: 168897284

  - id: 1868 # soneium
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0xE75Fc5eA6e74B824954349Ca351eb4e671ADA53a
        start_block: 6440817
      - name: MetaMorphoFactory
        address:
          - 0x7026b436f294e560b3C26E731f5cac5992cA2B33
        start_block: 6440899
      - name: MetaMorpho
        start_block: 6440899
      - name: AdaptiveCurveIRM
        address:
          - 0x68F9b666b984527A7c145Db4103Cc6d3171C797F
        start_block: 6440817
      - name: PreLiquidationFactory
        address:
          - 0xcBD0710425613d666C5Ffb4dE2eE73554F21c34B
        start_block: 6443359

  - id: 146 # sonic
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0xd6c916eB7542D0Ad3f18AEd0FCBD50C582cfa95f
        start_block: 9100931
      - name: MetaMorphoFactory
        address:
          - 0x0cE9e3512CB4df8ae7e265e62Fb9258dc14f12e8
        start_block: 9101319
      - name: MetaMorpho
        start_block: 9101319
      - name: AdaptiveCurveIRM
        address:
          - 0xDEfCf242226425f93d8DD0e314735C28517C473F
        start_block: 9100931
      - name: PreLiquidationFactory
        address:
          - 0xc72129DA4CC808e955699111b8c22B22Ca8A10b8
        start_block: 9102286

  - id: 480 # worldchain
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0xE741BC7c34758b4caE05062794E8Ae24978AF432
        start_block: 9025669
      - name: MetaMorphoFactory
        address:
          - 0x4DBB3a642a2146d5413750Cca3647086D9ba5F12
        start_block: 9025733
      - name: MetaMorpho
        start_block: 9025733
      - name: AdaptiveCurveIRM
        address:
          - 0x34E99D604751a72cF8d0CFDf87069292d82De472
        start_block: 9025669
      - name: PreLiquidationFactory
        address:
          - 0xe3cE2051a24e58DBFC0eFBe4c2d9e89c5eAe4695
        start_block: 10273494

  - id: 48900 # zircuit
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0xA902A365Fe10B4a94339B5A2Dc64F60c1486a5c8
        start_block: 14640172
      - name: MetaMorphoFactory
        address:
          - 0xd2c9068aD68c4c9F1A4fE1Ea650BdFE13DC5EaF1
        start_block: 14812082
      - name: MetaMorpho
        start_block: 14812082
      - name: AdaptiveCurveIRM
        address:
          - 0xBADb1809ecF658F36e31CcC980F72de029e1cE46
        start_block: 14640172
      - name: PreLiquidationFactory
        address:
          - 0x09d7629E82DdD80890495672201fe5FE1f909B0b
        start_block: 14812316

  - id: 143 # monad
    start_block: 0
    contracts:
      - name: Morpho
        address:
          - 0xD5D960E8C380B724a48AC59E2DfF1b2CB4a1eAee
        start_block: 31907457
      - name: MetaMorphoFactory
        address:
          - 0x33f20973275B2F574488b18929cd7DCBf1AbF275
        start_block: 32320327
      - name: MetaMorpho
        start_block: 32320327
      - name: AdaptiveCurveIRM
        address:
          - 0x09475a3D6eA8c314c592b1a3799bDE044E2F400F
        start_block: 31907457
      - name: PreLiquidationFactory
        address:
          - 0x273dBC3f178D03fA9D385e61Ee1E11dCf563EE14
        start_block: 32321504
